# jekyll
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate
# default front-matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: /assets/img/logo_banner.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Valerij Talagayev"
      comments: true
      permalink: /blog/:year/:month/:day/:title
  -
    scope:
      path: "assets/"
    values:
      sitemap: false
# blog pagination
paginate: 4
paginate_path: "/blog/page:num/"
# analytics
google_analytics: UA-139606105-1
# seo
url: "https://talagayev.github.io"
title: Valerij Talagayev
description: Valerij Talagayev's personnal website
author: Valerij Talagayev
logo: /assets/img/kz_logo.png
lang: en_US
twitter:
  username: talagayev
  card: summary_large_image
social:
  name: Valerij Talagayev
  links:
    - https://www.linkedin.com/in/valerij-talagayev-260bb820b/
    - https://github.com/talagayev
    - https://twitter.com/talagayev
